[package]
authors     = ["Metaverse <hello@mvs.org>"]
description = "FRAME pallet to back Ethereum assets"
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-ethereum-backing"
readme      = "README.md"
repository  = "https://github.com/hyperspace-network/hyperspace-common/"
version     = "1.3.0"

[dependencies]
# crates
codec      = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive"] }
serde      = { version = "1.0.118", optional = true }
serde_json = { version = "1.0.61", optional = true }
# hyperspace
array-bytes               = { default-features = false, path = "../../../../primitives/array-bytes" }
hyperspace-relay-primitives = { default-features = false, path = "../../../../primitives/relay" }
hyperspace-support          = { default-features = false, path = "../../../support" }
ethereum-primitives       = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# github
ethabi = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "with_no_std" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-io         = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[dev-dependencies]
# hyperspace
hyperspace-balances              = { path = "../../../../frame/balances" }
hyperspace-ethereum-linear-relay = { path = "../linear-relay" }
hyperspace-ethereum-relay        = { features = ["deserialize"], path = "../relay" }
hyperspace-relay-primitives      = { path = "../../../../primitives/relay" }
hyperspace-relayer-game          = { path = "../../relayer-game" }
hyperspace-staking               = { path = "../../../../frame/staking" }
ethereum-primitives            = { features = ["deserialize"], path = "../../../../primitives/ethereum-primitives" }
# github
rlp = { package = "rlp", git = "https://github.com/darwinia-network/parity-common.git" }
# substrate
pallet-session   = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-timestamp = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core          = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-staking       = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[features]
default = ["std"]

std = [
	"crates-std",
	"hyperspace-std",
	"github-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"serde",
	"serde_json",
]
hyperspace-std  = [
	"array-bytes/std",
	"hyperspace-relay-primitives/std",
	"hyperspace-support/std",
	"ethereum-primitives/std",
]
github-std    = ["ethabi/std"]
substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
