[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "Withdraw precompile for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "1.4.0"

[dependencies]
# hyperspace
hyperspace-evm-precompile-empty    = { default-features = false, path = "contracts/empty" }
hyperspace-evm-precompile-dna     = { default-features = false, path = "contracts/dna" }
hyperspace-evm-precompile-simple   = { default-features = false, path = "contracts/simple" }
hyperspace-evm-precompile-withdraw = { default-features = false, path = "contracts/withdraw" }

[features]
default = ["std"]

std = [
	"hyperspace-evm-precompile-empty/std",
	"hyperspace-evm-precompile-dna/std",
	"hyperspace-evm-precompile-simple/std",
	"hyperspace-evm-precompile-withdraw/std",
]
