[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
build       = "build.rs"
description = "FRAME pallet to linear relay Ethereum headers"
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-ethereum-linear-relay"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "1.4.0"

[dependencies]
# crates
codec      = { package = "parity-scale-codec", version = "1.3.7", default-features = false, features = ["derive"] }
serde      = { version = "1.0.124", optional = true }
serde_json = { version = "1.0.62", optional = true }
# hyperspace
hyperspace-support    = { default-features = false, path = "../../../support" }
ethereum-primitives = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# github
ethereum-types = { default-features = false, git = "https://github.com/new-mvs/parity-common.git" }
rlp            = { default-features = false, git = "https://github.com/new-mvs/parity-common.git" }
# substrate
frame-support = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }
frame-system  = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }
sp-runtime    = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }
sp-std        = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }

[dev-dependencies]
# crates
array-bytes = { version = "1.1.0" }
# hyperspace
hyperspace-balances   = { path = "../../../../frame/balances" }
ethereum-primitives = { features = ["deserialize"], path = "../../../../primitives/ethereum-primitives" }
# substrate
sp-core = { git = "https://github.com/new-mvs/substrate", branch = "latest" }
sp-io   = { git = "https://github.com/new-mvs/substrate", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"hyperspace-std",
	"github-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"serde",
	"serde_json",
]
hyperspace-std  = [
	"hyperspace-support/std",
	"ethereum-primitives/std",
]
github-std    = [
	"ethereum-types/std",
	"ethereum-types/serialize",
	"rlp/std",
]
substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]
