[package]
authors     = ["Metaverse <hello@mvs.org>"]
description = "Hyperspace CLI interface."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-cli"
readme      = "README.md"
repository  = "https://github.com/hyperspace-network/hyperspace-common/"
version     = "1.3.0"

[dependencies]
# crates
serde = { version = "1.0.118", features = ["derive"] }
toml  = { version = "0.5.7" }
# substrate
sc-cli        = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-service    = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-tracing    = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
