[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "BLAKE2 precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-blake2"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "1.4.0"


[dependencies]
# crates
hyperspace-evm-primitives = { default-features = false, path = "../../../../../primitives/evm" }
evm                     = { version = "0.22.0", default-features = false, features = ["with-codec"] }
# substrate
sp-core = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }
sp-io   = { default-features = false, git = "https://github.com/new-mvs/substrate", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"evm/std",
	"hyperspace-evm-primitives/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
