[package]
authors     = ["Metaverse <hello@mvs.org>"]
description = "Empty mock precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-empty"
readme      = "README.md"
repository  = "https://github.com/hyperspace-network/hyperspace-common/"
version     = "1.3.0"

[dependencies]
# crates
hyperspace-evm-primitives  = { default-features = false, path = "../../../../../primitives/evm" }
evm                      = { default-features = false, git = "https://github.com/darwinia-network/evm.git", branch = "darwinia", features = ["with-codec"] }

[features]
default = ["std"]

std = [
	"crates-std",
]

crates-std = [
	"hyperspace-evm-primitives/std",
	"evm/std",
]
