[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "Empty mock precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-empty"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "1.4.0"

[dependencies]
# crates
hyperspace-evm-primitives = { default-features = false, path = "../../../../../primitives/evm" }
evm                     = { version = "0.22.0", default-features = false, features = ["with-codec"] }

[features]
default = ["std"]

std = [
	"crates-std",
]

crates-std = [
	"hyperspace-evm-primitives/std",
	"evm/std",
]
