[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "Simple precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-simple"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.0.0"

[dependencies]
# crates
dp-evm    = { default-features = false, path = "../../../../../primitives/evm" }
evm       = { default-features = false, version = "0.23.0", features = ["with-codec"] }
ripemd160 = { default-features = false, version = "0.9" }
# substrate
sp-core = { default-features = false, git = "https://github.com/new-mvs/substrate.git", branch = "latest" }
sp-io   = { default-features = false, git = "https://github.com/new-mvs/substrate.git", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"dp-evm/std",
	"evm/std",
	"ripemd160/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
